/*
 * wall_control_define.h
 *
 *  Created on: 2016/09/06
 *      Author: PCーUSER
 */

#ifndef WALL_CONTROL_DEFINE_H_
#define WALL_CONTROL_DEFINE_H_

//ひふみんとを真ん中においた時のAD変換値
#define LEFT_WALL_REFERENCE 152 //左
#define RIGHT_WALL_REFERENCE 310 //右
#define FORWARDWALL_REFERENCE 310 //前
#define LEFT_FORWARDWALL_REFERENCE 134 //左斜め
#define RIGHT_FORWARDWALL_REFERENCE 126 //右斜め

#define LEFT_WALL_THRESHOLD 65 //左
#define RIGHT_WALL_THRESHOLD 130 //右
#define FORWARDWALL_THRESHOLD 180 //前
#define LEFT_FORWARDWALL_THRESHOLD 37 //左斜め
#define RIGHT_FORWARDWALL_THRESHOLD 50 //右斜め

#define LEFT_FORWARD_OBLIQUE_WALL_THRESHOLD 70
#define RIGHT_FORWARD_OBLIQUE_WALL_THRESHOLD 58
#define LEFT_OBLIQUE_WALL_THRESHOLD 200
#define RIGHT_OBLIQUE_WALL_THRESHOLD 200

//フェイルセーフ用
#define LEFT_WALL_FAIL 200 //左
#define RIGHT_WALL_FAIL 200 //右
#define FORWARDWALL_FAIL 200 //前
#define LEFT_FORWARDWALL_FAIL 600 //左斜め
#define RIGHT_FORWARDWALL_FAIL 600 //右斜め

#define WALL_FAIL_SAFE_DIFF 140 //死に判定用の甘さ厳しさ調整

#define RIGHT_WALL_OUT_THRESHOLD 342
#define LEFT_WALL_OUT_THRESHOLD 356

#define RIGHT_PILLAR_OUT_THRESHOLD 200
#define LEFT_PILLAR_OUT_THRESHOLD 115

//#define RIGHT_PILLAR_OUT_REFERENCE 175
//#define LEFT_PILLAR_OUT_REFERENCE 175

#define WALL_CONTROL 0.00017


#define LEFT_DECREASE_COUNT 5
#define RIGHT_DECREASE_COUNT 6

#define LEFT_FORWARD_OBLIQUE_WALL_CONTROL 0.00032
#define RIGHT_FORWARD_OBLIQUE_WALL_CONTROL 0.00030
#define LEFT_OBLIQUE_WALL_CONTROL 0.000
#define RIGHT_OBLIQUE_WALL_CONTROL 0.000

#define WALL_OUT_BEFORE_DISTANCE 0.045

#endif /* WALL_CONTROL_DEFINE_H_ */
